version: '3.1'

services:
  express:
    image: miroslawdubaj/webpack-hot-react-ts
    ports: 
      - "80:8080"
    volumes: 
      - ./:/usr/src/app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'mdubaj'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'example123'
    command: nodemon --legacy-watch ./bin/www
  mongo:
    image: mongo
    restart: always
    volumes: 
      - "/../mongodb-pstklient-datadir:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mdubaj'
      MONGO_INITDB_ROOT_PASSWORD: 'example123'
